### ISSUE TITLE
Revisar enumerats a la BBDD

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/distribucio#140]
Canviar els enumerats que guarden un valor a BBDD per valors varchar2 per evitar problemes quan s'esborrin o afegeixin valors obsolets. Actualment existeixen molts enumerats amb valors que no s'utilitzen que guarden el valor enter en comptes del valor del nom de l'enumerat. Això complica el manteniment dels enumerats.

**Comment by acuevas-dgtic** [comment]
Esta issue es antigua y puede estar relacionada con RuntimeException amb l'enumeració RegistreProcesEstatEnum #173
