### ISSUE TITLE
Revisar el sistema de logs

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/distribucio#141]
Adaptar la taula de logs per guardar millor la informació a mostrar a l'usuari en l'històric d'accions. Des de que es va separar de RIPEA hi ha una taula de logs per moviments i una altra per les accions amb només 2 paràmetres. Amb aquesta estructura de dades és difícil deixar correctament la informació del que ha passat a cada registre.

**Comment by acuevas-dgtic** [comment]
Revisar l'error de base de dades: ORA-12899: el valor es demasiado grande para la columna "DISTRIBUCIO"."DIS_CONT_LOG_PARAM"."VALOR" (real: 258, máximo: 256)
