### ISSUE TITLE
Revisar i corregir llargades dels camps de les anotacions

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/distribucio#142]
S'ha reportat que des de Regweb es campturen errors a l'hora de distribuir anotacions amb annexos amb títols superiors als 200 caràcters. S'ha de revisar que la llargada dels diferents camps de les anotacions de registre es corresponguin amb els estàndards SICRES i en el cas que se superi la llargada que s'abreugi el contingut en comptes de llençar error. S'haurà d'actualitzar el manual d'integracions amb els camps i les llargades màximes.

**Comment by acuevas-dgtic** [comment]
Esta issue es antigua. Hay que revisar si ya está implementada
