### ISSUE TITLE
Millorar velocitat de càrrega de la pantalla d'usuari

### ISSUE THREAD

**Issue by atrobat-dgtic** [GovernIB/distribucio#150]
Actualment tenim bústies que tenen mils d'anotacions de registre i els usuàris es queixen de la velocitat de càrrega de la pantalla i de l'aplicació de filtres. Ja es va fer fa un temps una revisió de la velocitat de càrrega d'aquesta pantalla però s'hi hauria de tornar dedicar un temps per veure si ho podem millorar més.

**Comment by acuevas-dgtic** [comment]
L’aplicació s’està fent servir amb intensitat. La pantalla principal del llistat d’anotacions pendents no es carrega. S’ha arribat a un temps de 7 a 10 minuts per carregar la pantalla.

**Comment by josepg-limit** [comment]
Aquesta incidència està molt relacionada amb la #157 en què distribució es queda sense connexions quan varis usuaris de forma concurrent executen la consulta de registres. Es treballa per optimitzar la consulta.
