### ISSUE TITLE
Marcar les anotacions de registre que s'han enviat per email

### ISSUE THREAD

**Issue by atrobat-dgtic** [GovernIB/distribucio#152]
Els usuaris demanen si seria possible que al llistat d'anotacions de registre sortis marcat amb un icona aquella anotació de registre que s'hagui enviat per email. També demanen si es podria filtrar les anotacions de registre enviades per email.

**Comment by acuevas-dgtic** [comment]
A l'estat d'enviat hauria de mostrar-se el destinatari, la data i l'hora d'enviament
