### ISSUE TITLE
Revisar el marcador d'anotacions pendents de processar

### ISSUE THREAD

**Issue by atrobat-dgtic** [GovernIB/distribucio#153]
El marcador d'anotacions pendents de processar que apareix a la part de dalt a la dreta de la pantalla d'usuari no s'actualitza com toca.

**Comment by josepg-limit** [comment]
Després de revisar l'error i el codi s'ha comprovat que el problema ha quedat resolt en la revisió 0.9.27 anterior amb la issue #157 Distribucio es queda sense connexions a BBDD
