### ISSUE TITLE
Actualitzar interficie d'integració amb registre per tractar metadades de digitalització

### ISSUE THREAD

**Issue by atrobat-dgtic** [GovernIB/distribucio#155]
S'han fet canvis a Registre per tal de que informi metadades de digitalització quan es fa una còpia autèntica d'un document. Actualment la interfície de comunicació entre registre i distribució no permet informar d'això i s'ha fet una nova versió que incorpora aquestes metadades.

**Comment by josepg-limit** [comment]
Es pensarà com versionar el WS d'alata d'anotacions i es contemplarà la possibiltiat d'afegir un paràmetre de metadades addicionals per poder enviar lliurement metadades a Distribució.
