### ISSUE TITLE
Optimitzar el temps que arriba l’anotació fins a la bústia.

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/distribucio#158]
Es detecten problemes de rendiment en processar una anotació. Quan es tarda excessivament en processar una anotació, la persona que l’ha enviada no té accés a l’anotació i qui l’hauria d’haver rebuda no la veu.

**Comment by josepg-limit** [comment]
Es modifica el sincronisme amb la tasca de guardar en segon pla per a que tingui prioritat l'alta d'anotacions.
