### ISSUE TITLE
Millora de regles. Regles encanedades

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/distribucio#159]
Aquesta millora consisteix en què després que arribi una anotació i s'apliqui una possible regla que mogui l'anotació a una bústia o la reenviï a una altra UO es torni a consultar si hi ha alguna regla automàtica aplicable per a la novabústia o UO, de manera que puguin aplicar les regles fins que no hi hagi cap regla aplicable o s'hagi trobat una aplicació cíclica de regles.
  Per facilitar la gestió de regles l'administrador disposarà d'una eina de simulació que li resumeixi les regles aplicables segons la informació de l'anotació.

 Botó per iniciar el simulador d'aplicació de regles:
![image](https://user-images.githubusercontent.com/17267008/96713206-88750e80-13a0-11eb-9670-7e794d5e0c41.png)

 Exemple de modal amb el resultat de la simulació entrant les dades de l'anotació a simular:
![image](https://user-images.githubusercontent.com/17267008/96713365-c40fd880-13a0-11eb-8fc8-2e768fdc464b.png)

**Comment by josepg-limit** [comment]
Aquesta issue "#159 Millorar els sistema de regles per al processament automàtic de documentació" s'ha dividit en 4 issues per a la millora del sistema de regles:

1. Millora de regles. Manteniment de backoffices #235
2. Millora de regles. Nou tipus de regla "reenviar a UO" #236
3. Millora de regles. Modificar definició de la regla #237
4. Millora de regles. Regles encanedades #159 (issue actual)
