### ISSUE TITLE
Modificar tamany de camps de la taula DIS_REGISTRE

### ISSUE THREAD

**Issue by atrobat-dgtic** [GovernIB/distribucio#171]
A Regweb es van modificar el tamany dels camps SOLICITA i EXPOSA i MOTIU_REBUIG de l'annexe de registre. Ara mos trobam que alguns registres no es poden distribuïr perquè a DISTRIBUCIÓ aquests camps són més petis. 
A DISTRIBUCIÓ tenim que a la taula DIS_REGISTRE:
- SOLICITA  es varchar(4000)
- EXPOSA  es varchar(4000)
- MOTIU_REBUIG  es varchar(4000)

I a registre aquests camps ara són del tipus CLOB. Per tant vos demanam que ens passeu aquests camps a CLOB.

**Comment by josepg-limit** [comment]
La modificació ha afectat a la consulta de la bústia d'usuaris issue
#150 i també s'ha arreglat la issue d'ordenació per remitent #170.
