### ISSUE TITLE
RuntimeException amb l'enumeració RegistreProcesEstatEnum

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/distribucio#173]
S'han detectat errades recurrents del tipus java.lang.RuntimeException amb l'enumeració RegistreProcesEstatEnum:

`org.springframework.dao.InvalidDataAccessApiUsageException:  Unknown name value for enum  lass  es.caib.distribucio.core.api.registre.RegistreProcesEstatEnum:  DISTRIBUIT_PROCESSAT; nested exception is  java.lang.IllegalArgumentException: Unknown name value for enum class  es.caib.distribucio.core.api.registre.RegistreProcesEstatEnum:  DISTRIBUIT_PROCESSAT`

`org.springframework.dao.InvalidDataAccessApiUsageException: Unknown name value for enum class es.caib.distribucio.core.api.registre.RegistreProcesEstatEnum: PENDENT; nested exception is java.lang.IllegalArgumentException: Unknown name value for enum class es.caib.distribucio.core.api.registre.RegistreProcesEstatEnum: PENDENT`

**Comment by josepg-limit** [comment]
L'error es devia a que hi havia valors per enumerats antics, s'han corregit amb un script d'actualtizació.
