### ISSUE TITLE
Revisar els rols de les bústies sense codi dir3

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/distribucio#181]
Els rols de les bústies que no tenen un codi dir3 associat no funcionen. Hem d'assignar el codi d'usuari directament als permisos, encara que l'usuari tingui assignat el rol específic de la bústia..

**Comment by josepg-limit** [comment]
Per solucionar aquesta incidència s'afegira la opció "Desconnectar" al menú del usuari, per tancar sessió i en tornar iniciar sessió els rols es refrescarien per l'usuari.
