### ISSUE TITLE
Recordar la posició en el llistat si es produeix un error

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/distribucio#183]
Si es produeix un error (per exemple, l'adreça de correu no és correcta), torna a l'inici de la pàgina. S'hauria de mantenir la posició mostrant l'error en una venta modal si es necessari).

![imatge](https://user-images.githubusercontent.com/58417501/86343615-7fc5c480-bc59-11ea-83bf-0e974b8e50d2.png)

**Comment by josepg-limit** [comment]
Aquesta issue es va solucionar amb les optimitzacions del mail
