### ISSUE TITLE
A la pantalla de consulta d'anotacions de registre d'administrador apareix bloquejat el camp bústia del filtre

### ISSUE THREAD

**Issue by atrobat-dgtic** [GovernIB/distribucio#194]
A la pantalla de consulta d'anotacions de registre d'administrador apareix bloquejat el camp bústia del filtre. Mos agradaria que es pogués filtrar les anotacions de registre per bústia.

[filtre.pdf](https://github.com/GovernIB/distribucio/files/4923875/filtre.pdf)

**Comment by josepg-limit** [comment]
El camp bústia apareixia bloquejat fins que es seleccioni un unitat organitzativa.
S'ha canviat per a que es pugui seleccionar un bustia sense tenir que seleccionar una unitat organitzativa.
