### ISSUE TITLE
Revisar i millorar el temps de processament des de que arriba l'anotació fins que es guarden els annexos

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/distribucio#272]
S'ha reportat que hi ha anotacions que estan més de 2h des de que arriba l'anotació fins que els annexos es guarden a l'Arxiu. S'ha de revisar com es pot millorar el temps de processament de les anotacions.

**Comment by acuevas-dgtic** [comment]
![imatge](https://user-images.githubusercontent.com/58417501/107355042-3e3ea700-6acf-11eb-9286-baa017ff32c0.png)

**Comment by josepg-limit** [comment]
Finalment en aquesta issue s'han reduït el nombre de peticions que es fan a l'Arxiu. Per a la propera versió es dona d'alta la issue #282 per processar en paral·lel anotacions de registre pendents de l'Arxiu.
