### ISSUE TITLE
Poder marcar bústies com a favorits

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/distribucio#297]
Els usuaris es queixen que l'arbre és molt gran i que té moltes bústies.
I que realment, sempre estan treballant amb les mateixes bústies.

Per això, han demanat si seria possible crear una secció a l'esquerra de l'arbre.

I que aquesta secció només aparegui si hi ha favorits definits. Els favorits es definirien a nivell de cada usuari. És a dir, cada usuari definiria els seus. I òbviament, aquests favorits s'haurien de poder donar d'alta i eliminar.

La forma de donar d'alta seria amb el menú de context tipus el de "Afegeix per coneixement" (#295). Però amb una opció que es digui "Afegir a favorits".

Un usuari hauria de poder seleccionar dels favorits si vol enviar per Processar/tramitar o Coneixement.

Si se seleccionen per a tramitació/coneixement es marcaran dins l'arbre amb el color corresponent.

**Comment by acuevas-dgtic** [comment]
Els camps comentari i Deixar còpia en bústia actual  haurien d'ocupar tota la finestra, no només una columna

**Comment by acuevas-dgtic** [comment]
Error d'ortografia: Ha de dir "Mostrar només bústies favorites" i "bústies seleccionades"

![imatge](https://user-images.githubusercontent.com/58417501/118632711-fa93c180-b7d0-11eb-8327-42b81501a983.png)

**Comment by acuevas-dgtic** [comment]
El filtre "Mostrar només bústies favorites" no ha de mostrar les unitats que no tenen bústies favorites.
