### ISSUE TITLE
Permetre descarregar annexos sense custodiar des del correu electrònic

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/distribucio#302]
Si s'han esgotat tots els re intents de custòdia dins l'arxiu i l'usuari envia l'anotació per correu electrònic no es poden descarregar els documents. S'ha de preveure qualque mecanisme per poder-se descarregar aquest documents que no estan dins l'arxiu.

**Comment by josepg-limit** [comment]
L'error es devia a que faltava definir la url base de Distribucio per construir els enllaços a l'entorn de proves.
