### ISSUE TITLE
Error quan se marquen varies anotacions

### ISSUE THREAD

**Issue by santich-dgtic** [GovernIB/distribucio#304]
Quan se marquen varies anotacions, (en estat pendent de l'usuari) per possar-les com a procesades, se produeix un error: Caller unauthorized (RoleBasedAuthorizationInterceptorv2.java)

**Comment by josepg-limit** [comment]
Issue duplicada de la issue #307 Error EJBAccessException processant anotacions de forma múltiple, es procedeix a tancar.
