### ISSUE TITLE
Afegir bústies favorites o bústies freqüents

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/distribucio#315]
Possibilitar que en Reexpedir un assentament, que sali l'arbre de les diferents bústies de destí existents, s'afegeixi un apartat de "bústies favorites o bústies freqüents" que l'usuari pugui seleccionar, i així no haver de desplegar l'arbre (normalment dues vegades punxar el triangulito) cada vegada per a cada registre.

**Comment by acuevas-dgtic** [comment]
duplicat #297 ? És lo mateix?

**Comment by josepg-limit** [comment]
Finalment s'unifica amb la issue #297 i en aquesta issue en comptes de posar el menú contextual es posen dos botons al costat de la bústia i un check per veure només les bústies freqüents o preferides. També es passa a la versió 0.9.35
