### ISSUE TITLE
Actualitzar documentació

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/distribucio#322]
Actualitzar el manual d'usuari i el manual d'integració (tasques APB).

**Comment by bgual-dgtic** [comment]
També (si no ha de canviar el funcionament de reenviar a una altre bústia) podeu aclarar que si es reenvia una anotació a una nova bústia, aquesta anotació es marcarà com pendent d'usuari?
Han arribat consultes de reenviaments que s'han equivocat de destí i era relacionat amb això, que no sortia al manual

**Comment by bgual-dgtic** [comment]
També s'haurien de detallar les cridades SOAP i els paràmetres d'aquestes al manual d'integració.

**Comment by acuevas-dgtic** [comment]
Veo que solo se ha actualizado el manual de usuario. Falta actualizar el manual de integración
