### ISSUE TITLE
Posar per defecte el Localitzador d'anotacions de registre al perfil Administrador

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/distribucio#328]
La pàgina per defecte quan entres com administrador hauria de ser el Localitzador d'anotacions de registre . Actualment és la gestió de bústies

**Comment by josepg-limit** [comment]
Aquesta issue ja queda resolta amb la issue #321 Navegar al llistat d'anotacions quan s'esculli el rol d'Administrador de la versió 0.9.36
