### ISSUE TITLE
Modificar filtre pantalla de moviments

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/distribucio#331]
S'ha de modificar la pantalla de moviments per filtrar amb bústia origen i destí.

**Comment by bgual-dgtic** [comment]
Revisant la pantalla de moviments he vist una cosa:
veig que tant al camp d'origen i de destí agafa les bústies a les que l'usuari té accés. A destí és correcte, però a origen no deuria ser, al menys tendria que agafar un llistat de les bústies d'origen que surten a la taula de moviments
