### ISSUE TITLE
Modificar la configuració d'autenticació dels backoffices

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/distribucio#359]
Ens hem adonat d'un problema en la gestió de backoffices. Actualment cal indicar l'url, usuari i contrasenya però això incompleix els nostres estàndards de desenvolupament ja que totes les credencials s s'han d'indicar en el fitxer de propietats del jboss. Per tant, hi hauria de modificar aquest comportament

**Comment by josepg-limit** [comment]
Se van a añadir cambios para que acceda al fichero de propiedades solo cuando el valor para el campo usuario o password tenga el formato ${claveficheropropiedades}, manteniendo así la posibilidad de configurar el usuario y password directamente en el formulario. 
De esta manera no se interfiere con al APB y nos da agilidad en entornos de pruebas y desarrollo.
