### ISSUE TITLE
Mostrar fitxers tècnics (XML) en la secció d'annexos d'una anotació de registre que només sigui visible pels administradors

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/distribucio#364]
Aquest fitxers tècnics seran bàsicament els rebuts mitjançant tràmits telemàtics (generalment el formulari de dades)

**Comment by josepg-limit** [comment]
Además de en el detalle de la anotación para el rol Usuari, también se han ocultado los ficheros técnicos XML en el envío de anotaciones vía email, tanto individual como masivo, con rol Usuari. Para el rol Administrador se siguen mostrando tanto en el detalle como en el email enviado.
