### ISSUE TITLE
Permetre generar ZIP encara que hi hagi annexos no custodiats dins l'arxiu

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/distribucio#432]
Si hi ha annexos que no s'ha pogut guardar dins l'arxiu, la generació del ZIP dóna error, encara que es poden descarregar tots els annexos de forma individual. Si qualque document no està dins l'arxiu s'hauria d'afegir el document des de filsystem (si existeix) i si no està no afegir-lo al ZIP per evitar l'error (mostrant un missatge)

**Comment by bgual-dgtic** [comment]
Tenir en compte el següent:
A vegades arriben de registre pdf generats pels usuaris amb una aplicació obsoleta i venen mal generats, això fa que el itext de concsv doni un error i no es pugui generar la versió imprimible (y tampoc descarregar cap versió).
S'hauria de controlar que quan la imprimible no es pugui generar, fiqui al .zip l'original.
Adjunto captura del problema als pdf (es pot veure obrint el pdf al notepad++)
![imatge](https://user-images.githubusercontent.com/82584534/158997832-a4e5bb8a-5aa1-49cf-9ced-8cc1c369d2cd.png)
Crea el CreatorDate(, però no ho acaba de tancar mai.

**Comment by acuevas-dgtic** [comment]
He intentado generar el zip de la anotación GOIBE2255/2022 y me ha dado error. Esta anotación tiene un documento que no está custodiado

**Comment by acuevas-dgtic** [comment]
`S'ha produït un error descarregant el document: Error generant el .zip de documentació pel registre GOIBE2255/2022 amb ID 1383939 : 1 errors generant el .zip Error afegint l'annex Deducción por renta del registre GOIBE2255/2022 al document zip comprimit: null`
