### ISSUE TITLE
Canviar el nom de la versió imprimible dels annexes a NOM_ORIGINAL_imprimible

### ISSUE THREAD

**Issue by bgual-dgtic** [GovernIB/distribucio#434]
Per millorar la visibilitat al descarregar els imprimibles quan es descarreguen un a un

**Comment by acuevas-dgtic** [comment]
Hay un error. La pestaña "Resum" ha de permitir descargar el documento original como hasta ahora (no la versión imprimible). Además, el boton de versióin imprimible solo muestra el nombre original, no  NOM_ORIGINAL_imprimible

**Comment by acuevas-dgtic** [comment]
Perdon, lo había probado mal. El funcionamiento parece correcto
