### ISSUE TITLE
Afegir l'acció exportar a full de cálcul en la DataTable dels usuaris

### ISSUE THREAD

**Issue by bgual-dgtic** [GovernIB/distribucio#438]
Es a dir, que puguin marcar les anotacions a exportar en un .ods o .xlsx.
La informació a mostrar a les columnes hauria de ser la mateixa que la Datatable:

- Número
- Títol
- Documentació: que mostri el número d'anexes (sense contar els .xml tècnics). 
- Número origen
- Data pujada registre
- Data presentació (A vegades no coincideix perque han enregistrat a un altre organisme)
- Remitent, si es una oficina d'origen, afegir el codi.
- Bústia, DIR3 i nom de la bústia
- Interessats

**Comment by acuevas-dgtic** [comment]
Aquesta funcionalitat ja existeix des de fa vàries versions. No sé si s'han fet canvis en aquesta issue (no veig commits).
