### ISSUE TITLE
Al reprocessar una anotació amb molts d'anexes, dóna error, no mostra la traça d'error al detall ni ho reconeix com un intent

### ISSUE THREAD

**Issue by bgual-dgtic** [GovernIB/distribucio#498]
![image](https://user-images.githubusercontent.com/82584534/180767487-e248e265-f9e6-4ffd-b1d1-5379536907de.png)
De moment, com a mínim, falla amb 25 anexes, també o fa amb 40 i 50

**Comment by josepg-limit** [comment]
Aquesta issue ja està resolta a la issue 460 de la versió 0.9.44
