### ISSUE TITLE
Error:  JsonMappingException: No content to map due to end-of-input

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/distribucio#511]
Ho ha casos on falla el procés automàtic de guardar annexos. Es soluciona pitjant el botó "Reintentar processament" però s'hauria de revisar per automatizar-lo.
```
Error al crear el document annex (Titol=XXXX.pdf) a dins el contenidor: JsonMappingException: No content to map due to end-of-input
 at [Source: ; line: 1, column: 1]
```

![image](https://user-images.githubusercontent.com/58417501/190340777-2232e008-3ec8-4185-b6cf-c1a7580ecd88.png)

**Comment by josepg-limit** [comment]
Aquest problema es passa perquè el PluginArxiuCaib no pot interpretar la resposta de l'Arxiu quan retorna un Json amb salts de línia. Se pot resoldre des de l'arxiu o des del PluginArxiuCaib, s'està estudiant quina és la millor forma i s'obrirà una nova issue a Distribució en cas de que sigui necessari.
