### ISSUE TITLE
Mostrar la informació del backoffice per l'anotació de registre

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/distribucio#531]
Es proposa mostrar el codi de backoffice en la columna d'estat i en el detall de l'anotació quan l'anotació de registre tingui un estat relacionat amb un backoffice.

**Comment by acuevas-dgtic** [comment]
Modificar el text "Processada pel backoffice helium " per "Processada per Helium" tant a la columna estat com al detall d el'anotació
