### ISSUE TITLE
Afegir la opció "Cap procediment" a l'inici del select de procediments de l'acció de classificar anotació

### ISSUE THREAD

**Issue by bgual-dgtic** [GovernIB/distribucio#555]
Això es per a poder treure de "rebutjada al backoffice" les anotacions que han estat enregistrades amb un SIA per error quan no han de tindre SIA. Al llevar el SIA hauria de passar a "Pendent d'usuari"
![image](https://user-images.githubusercontent.com/82584534/205288105-73473f3c-e783-4df0-9551-ef0725a38eea.png)

**Comment by acuevas-dgtic** [comment]
Millor poder eliminar (amb una creu al costat) el procediment seleccionat prèviament . D'aquesta manera, el camp deixaria de ser obligatori.

**Comment by josepg-limit** [comment]
Es reobre per corregir-la i treure el codi de procediment, actualment queda informat tot i prèmer la X per posar el procediment com a nul.

**Comment by josepg-limit** [comment]
![x_procediments3](https://github.com/GovernIB/distribucio/assets/17267008/5960a52b-019a-45ce-ae2a-f208997f06a6)

**Comment by josepg-limit** [comment]
Es valida i tanca la issue
