### ISSUE TITLE
No deixa marcar com a processar una anotació rebutjada per un backoffice

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/distribucio#559]
![image](https://user-images.githubusercontent.com/58417501/209772369-13a67858-aefc-4da6-bf0c-f22631780b1d.png)

**Comment by acuevas-dgtic** [comment]
L'ha hem classificat amb altre procediment però no ens deixa

**Comment by acuevas-dgtic** [comment]
La opción de marcar como procesada continua deshabilitada en el perfil usuario. En el perfil administrador si la veo habilitada

**Comment by josepg-limit** [comment]
![rebutadas](https://github.com/GovernIB/distribucio/assets/17267008/fb0a522a-3c26-4640-bca2-a6af09ab1454)
