### ISSUE TITLE
Afegir codi SIA al desplegable de la classificació de múltiples anotacions

### ISSUE THREAD

**Issue by bgual-dgtic** [GovernIB/distribucio#565]
![image](https://user-images.githubusercontent.com/82584534/212843409-2b9cc53a-ea70-46ef-bc21-bb288e0bf540.png)
Ara mateix no apareix el SIA al desplegable.
També afegir un filtre per a millorar la cerca de procediments

**Comment by josepg-limit** [comment]
S'ha revisat i s'ha corregit amb la issue #568.
