### ISSUE TITLE
Veure "Número expedient" al costat de "Procediment" al resum de les anotacions

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/distribucio#579]
Veure "Número expedient" al costat de "Procediment" al resum de les anotacions:

![imagen](https://user-images.githubusercontent.com/17267008/225595061-fbaf23b4-ddc2-4332-81d0-d532515d0376.png)

**Comment by acuevas-dgtic** [comment]
Parece que no se muestra bien

![image](https://github.com/GovernIB/distribucio/assets/58417501/9449e668-a50a-4987-8323-73ac33f18a2e)
