### ISSUE TITLE
Reduir la informació del monitor d'integracions

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/distribucio#589]
Es demana reduir la informació que s'enregistra a les taules del monitor d'integració per evitar problemes de BBDD. Els canvis a realitzar són:
- Treure la integració amb els usuaris.
- No enregistrar les dades dels paràmetres per les peticions que s'han realitzat correctament.
- Millorar algunes descripcions de les integracions per evitar haver d'obrir el detall.

**Comment by acuevas-dgtic** [comment]
Añadir una columna en la pestana Backoffice para indicar el nombre del backoffice
