### ISSUE TITLE
Afegir client API REST per les regles

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/distribucio#592]
Modificar el projecte distribucio-rest-client per afegir un client API REST per l'API de creació de regles. Posar el client d'integració actual en un nou paquet diferenciat en el projecte.

**Comment by acuevas-dgtic** [comment]
Actualitzar la secció del client en el manual d'integració

**Comment by josepg-limit** [comment]
![Captura de pantalla 2023-05-17 080806](https://github.com/GovernIB/distribucio/assets/17267008/16c0cac8-75ab-44ac-8fe6-78cc8b051408)
