### ISSUE TITLE
Si els permisos d'una bústia estan mal definits apareix un error al accedir-hi

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/distribucio#630]
En la gestió d'una bústia en concret apareix un error Ajax

![image](https://github.com/GovernIB/distribucio/assets/58417501/4de34718-69d8-40ad-bf86-bd72aa582140)

L'error desapareix si activam la propietat es.caib.distribucio.mostrar.usuaris.inactius.ldap però s'hauria de controlar sense tenir que activar-la.

L'error era causat a que el tipus de permis estava definit com "Usuari " en lloc de "Rol"
![image](https://github.com/GovernIB/distribucio/assets/58417501/b1eea9f4-48cf-47ed-813f-16a5c30be6e2)

**Comment by josepg-limit** [comment]
Es revisa i es comprova que aquesta issue ja es va resoldre durant les correccions de la versió 1.0.1.
