### ISSUE TITLE
Amb el rol d'usuari no apareixen tots els moviments dels reenviaments amb còpia a altres bústies

### ISSUE THREAD

**Issue by bgual-dgtic** [GovernIB/distribucio#636]
Aquesta es la informació que no apareix com a usuari
![image](https://github.com/GovernIB/distribucio/assets/82584534/40c2d521-fbd5-4cb7-a945-cd74261ae067)

**Comment by josepg-limit** [comment]
Es revisa i no es pot reproduir. És probable que l'usuari estigués visualitzant una anotació còpia que no conté tots els moviments de l'original.
