### ISSUE TITLE
Error al borrar backoffice y reglas

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/distribucio#646]
al borrar backoffice dóna l'error 
`ORA-02292: restricción de integridad (DISTRIBUCIO.DIS_BACKOFFICE_DESTI_REGLA_FK) violada - registro secundario encontrado `

al borrar una regla desactivada: 
`Hi ha hagut un error esborrant la regla: class javax.ejb.EJBException: es.caib.distribucio.core.api.exception.ValidationException: No es pot esborrar la regla amb anotacions connectat (reglaId=217621159) `

**Comment by josepg-limit** [comment]
Es mostra un missatge d'error controlat a l'usuari.
